from approvalhandlers.approvalhandler import ApprovalHandler
from approvalhandlers.monsterkchandler import MonsterKCHandler
from approvalhandlers.cloghandler import ClogHandler
from approvalhandlers.pestcontrolhandler import PestControlHandler
from approvalhandlers.lmshandler import LMSHandler
from approvalhandlers.mtahandler import MTAHandler
from approvalhandlers.tithefarmhandler import TitheFarmHandler
from approvalhandlers.farmingcontractshandler import FarmingContractsHandler